spring:
  application:
    name: movie-service
eureka:
  instance:
    instance-id: movie-service
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
ribbon:
  eureka:
    enabled: true
feign:
  hystrix:
    enabled: false
logging:
  level:
    org:
      wzx:
        cloud:
          movie: debug
