spring:
  application:
    name: system-service

management:
  endpoints:
    web:
      exposure:
        include:  ["routes","health"]

logging:
  level:
    org:
      wzx:
        cloud: debug




